//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoManager.UI.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoManager.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string About_Title => ResourceManager.GetString("About_Title", resourceCulture);
        public static string About_Version => ResourceManager.GetString("About_Version", resourceCulture);
        public static string About_Copyright => ResourceManager.GetString("About_Copyright", resourceCulture);
        public static string About_Description => ResourceManager.GetString("About_Description", resourceCulture);
        public static string ApplicationTitle => ResourceManager.GetString("ApplicationTitle", resourceCulture);
        public static string Browse => ResourceManager.GetString("Browse", resourceCulture);
        public static string Button_Run => ResourceManager.GetString("Button_Run", resourceCulture);
        public static string Button_Scan => ResourceManager.GetString("Button_Scan", resourceCulture);
        public static string Button_SelectOutput => ResourceManager.GetString("Button_SelectOutput", resourceCulture);
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);
        public static string CheckBox_PreserveOriginals => ResourceManager.GetString("CheckBox_PreserveOriginals", resourceCulture);
        public static string Column_DateSource => ResourceManager.GetString("Column_DateSource", resourceCulture);
        public static string Column_SourceFile => ResourceManager.GetString("Column_SourceFile", resourceCulture);
        public static string Column_Status => ResourceManager.GetString("Column_Status", resourceCulture);
        public static string Column_TargetLocation => ResourceManager.GetString("Column_TargetLocation", resourceCulture);
        public static string Completed => ResourceManager.GetString("Completed", resourceCulture);
        public static string DestinationDirectory => ResourceManager.GetString("DestinationDirectory", resourceCulture);
        public static string Dialog_SelectFolder => ResourceManager.GetString("Dialog_SelectFolder", resourceCulture);
        public static string Dialog_SelectOutputDirectory => ResourceManager.GetString("Dialog_SelectOutputDirectory", resourceCulture);
        public static string Error => ResourceManager.GetString("Error", resourceCulture);
        public static string Error_CouldNotOpenImage => ResourceManager.GetString("Error_CouldNotOpenImage", resourceCulture);
        public static string Error_Title => ResourceManager.GetString("Error_Title", resourceCulture);
        public static string Files_Header => ResourceManager.GetString("Files_Header", resourceCulture);
        public static string FileSize_Bytes => ResourceManager.GetString("FileSize_Bytes", resourceCulture);
        public static string FileSize_Gigabytes => ResourceManager.GetString("FileSize_Gigabytes", resourceCulture);
        public static string FileSize_Kilobytes => ResourceManager.GetString("FileSize_Kilobytes", resourceCulture);
        public static string FileSize_Megabytes => ResourceManager.GetString("FileSize_Megabytes", resourceCulture);
        public static string Menu_About => ResourceManager.GetString("Menu_About", resourceCulture);
        public static string Menu_Help => ResourceManager.GetString("Menu_Help", resourceCulture);
        public static string Metadata_NotDetected => ResourceManager.GetString("Metadata_NotDetected", resourceCulture);
        public static string Metadata_NotFound => ResourceManager.GetString("Metadata_NotFound", resourceCulture);
        public static string OperationCancelled => ResourceManager.GetString("OperationCancelled", resourceCulture);
        public static string OutputPath_Label => ResourceManager.GetString("OutputPath_Label", resourceCulture);
        public static string OutputPath_Placeholder => ResourceManager.GetString("OutputPath_Placeholder", resourceCulture);
        public static string Preview_Header => ResourceManager.GetString("Preview_Header", resourceCulture);
        public static string Processing => ResourceManager.GetString("Processing", resourceCulture);
        public static string Property_EXIF_IFD0 => ResourceManager.GetString("Property_EXIF_IFD0", resourceCulture);
        public static string Property_EXIF_SubIFD => ResourceManager.GetString("Property_EXIF_SubIFD", resourceCulture);
        public static string Property_FileCreated => ResourceManager.GetString("Property_FileCreated", resourceCulture);
        public static string Property_Filename => ResourceManager.GetString("Property_Filename", resourceCulture);
        public static string Property_FileModified => ResourceManager.GetString("Property_FileModified", resourceCulture);
        public static string Property_GPS => ResourceManager.GetString("Property_GPS", resourceCulture);
        public static string PropertyGrid_Header => ResourceManager.GetString("PropertyGrid_Header", resourceCulture);
        public static string Ready => ResourceManager.GetString("Ready", resourceCulture);
        public static string SelectSourceDirectory => ResourceManager.GetString("SelectSourceDirectory", resourceCulture);
        public static string SourceDirectory => ResourceManager.GetString("SourceDirectory", resourceCulture);
        public static string SourceDirectoryNotExist => ResourceManager.GetString("SourceDirectoryNotExist", resourceCulture);
        public static string SourcePaths_Header => ResourceManager.GetString("SourcePaths_Header", resourceCulture);
        public static string StartProcessing => ResourceManager.GetString("StartProcessing", resourceCulture);
        public static string Status_CalculatingTargets => ResourceManager.GetString("Status_CalculatingTargets", resourceCulture);
        public static string Status_FilesFound => ResourceManager.GetString("Status_FilesFound", resourceCulture);
        public static string Status_FilesFoundReady => ResourceManager.GetString("Status_FilesFoundReady", resourceCulture);
        public static string Status_ScanError => ResourceManager.GetString("Status_ScanError", resourceCulture);
        public static string Status_Scanning => ResourceManager.GetString("Status_Scanning", resourceCulture);
        public static string Status_ScanningFiles => ResourceManager.GetString("Status_ScanningFiles", resourceCulture);
        public static string Status_SelectSourcePaths => ResourceManager.GetString("Status_SelectSourcePaths", resourceCulture);
        public static string Status_TargetCalculationError => ResourceManager.GetString("Status_TargetCalculationError", resourceCulture);
        public static string TargetLocation_Calculating => ResourceManager.GetString("TargetLocation_Calculating", resourceCulture);
        public static string TreeView_AddPath => ResourceManager.GetString("TreeView_AddPath", resourceCulture);
        public static string TreeView_NonRecursive => ResourceManager.GetString("TreeView_NonRecursive", resourceCulture);
        public static string TreeView_Recursive => ResourceManager.GetString("TreeView_Recursive", resourceCulture);
        public static string TreeView_RemovePath => ResourceManager.GetString("TreeView_RemovePath", resourceCulture);
        public static string TreeView_ToggleRecursive => ResourceManager.GetString("TreeView_ToggleRecursive", resourceCulture);
    }
}
