//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoManager.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoManager.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Manager.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Button_Run {
            get {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Files.
        /// </summary>
        internal static string Button_Scan {
            get {
                return ResourceManager.GetString("Button_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string Column_SourceFile {
            get {
                return ResourceManager.GetString("Column_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Location.
        /// </summary>
        internal static string Column_TargetLocation {
            get {
                return ResourceManager.GetString("Column_TargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Column_Status {
            get {
                return ResourceManager.GetString("Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Source.
        /// </summary>
        internal static string Column_DateSource {
            get {
                return ResourceManager.GetString("Column_DateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string Dialog_SelectFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &Help.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &About....
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Path....
        /// </summary>
        internal static string TreeView_AddPath {
            get {
                return ResourceManager.GetString("TreeView_AddPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Path.
        /// </summary>
        internal static string TreeView_RemovePath {
            get {
                return ResourceManager.GetString("TreeView_RemovePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Recursive.
        /// </summary>
        internal static string TreeView_ToggleRecursive {
            get {
                return ResourceManager.GetString("TreeView_ToggleRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path:.
        /// </summary>
        internal static string OutputPath_Label {
            get {
                return ResourceManager.GetString("OutputPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (organize in-place if empty).
        /// </summary>
        internal static string OutputPath_Placeholder {
            get {
                return ResourceManager.GetString("OutputPath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output....
        /// </summary>
        internal static string Button_SelectOutput {
            get {
                return ResourceManager.GetString("Button_SelectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Recursive).
        /// </summary>
        internal static string TreeView_Recursive {
            get {
                return ResourceManager.GetString("TreeView_Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Non-recursive).
        /// </summary>
        internal static string TreeView_NonRecursive {
            get {
                return ResourceManager.GetString("TreeView_NonRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output directory (leave empty to organize in-place).
        /// </summary>
        internal static string Dialog_SelectOutputDirectory {
            get {
                return ResourceManager.GetString("Dialog_SelectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (don't move).
        /// </summary>
        internal static string CheckBox_PreserveOriginals {
            get {
                return ResourceManager.GetString("CheckBox_PreserveOriginals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select source paths first.
        /// </summary>
        internal static string Status_SelectSourcePaths {
            get {
                return ResourceManager.GetString("Status_SelectSourcePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning files....
        /// </summary>
        internal static string Status_ScanningFiles {
            get {
                return ResourceManager.GetString("Status_ScanningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} image files.
        /// </summary>
        internal static string Status_FilesFound {
            get {
                return ResourceManager.GetString("Status_FilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} image files - Ready.
        /// </summary>
        internal static string Status_FilesFoundReady {
            get {
                return ResourceManager.GetString("Status_FilesFoundReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan error: {0}.
        /// </summary>
        internal static string Status_ScanError {
            get {
                return ResourceManager.GetString("Status_ScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated {0}/{1} target locations.
        /// </summary>
        internal static string Status_CalculatingTargets {
            get {
                return ResourceManager.GetString("Status_CalculatingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating target locations: {0}.
        /// </summary>
        internal static string Status_TargetCalculationError {
            get {
                return ResourceManager.GetString("Status_TargetCalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        internal static string TargetLocation_Calculating {
            get {
                return ResourceManager.GetString("TargetLocation_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not detected.
        /// </summary>
        internal static string Metadata_NotDetected {
            get {
                return ResourceManager.GetString("Metadata_NotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Metadata_NotFound {
            get {
                return ResourceManager.GetString("Metadata_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string FileSize_Bytes {
            get {
                return ResourceManager.GetString("FileSize_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string FileSize_Kilobytes {
            get {
                return ResourceManager.GetString("FileSize_Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string FileSize_Megabytes {
            get {
                return ResourceManager.GetString("FileSize_Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string FileSize_Gigabytes {
            get {
                return ResourceManager.GetString("FileSize_Gigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open image: {0}.
        /// </summary>
        internal static string Error_CouldNotOpenImage {
            get {
                return ResourceManager.GetString("Error_CouldNotOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
    }
}