using System.Globalization;
using Hawkynt.PhotoManager.Core.Develop;

namespace Hawkynt.PhotoManager.Tests.Unit.Develop;

[TestFixture]
public class LutLoaderTests {
  [Test]
  public void ParseCube_MinimalIdentitySize2_LoadsAllEightVertices() {
    // 2³ = 8 triplets in 0..1 forming the identity cube.
    const string text = """
LUT_3D_SIZE 2
0.0 0.0 0.0
1.0 0.0 0.0
0.0 1.0 0.0
1.0 1.0 0.0
0.0 0.0 1.0
1.0 0.0 1.0
0.0 1.0 1.0
1.0 1.0 1.0
""";
    var lut = LutLoader.ParseCube(text);
    Assert.Multiple(() => {
      Assert.That(lut.Size, Is.EqualTo(2));
      Assert.That(lut.Table.Length, Is.EqualTo(8 * 3));
      Assert.That(lut.Table[0],  Is.EqualTo(0f));   // (0,0,0) → black
      Assert.That(lut.Table[3],  Is.EqualTo(1f));   // (1,0,0) → r=1
      Assert.That(lut.Table[21], Is.EqualTo(1f));   // (1,1,1).R
      Assert.That(lut.Table[22], Is.EqualTo(1f));   // (1,1,1).G
      Assert.That(lut.Table[23], Is.EqualTo(1f));   // (1,1,1).B
    });
  }

  [Test]
  public void ParseCube_RejectsMissingSizeHeader() {
    const string text = "0.0 0.0 0.0\n1.0 1.0 1.0\n";
    Assert.Throws<FormatException>(() => LutLoader.ParseCube(text));
  }

  [Test]
  public void ParseCube_RejectsBadSampleCount() {
    var text = "LUT_3D_SIZE 2\n" + string.Concat(Enumerable.Repeat("0.0 0.0 0.0\n", 4));
    Assert.Throws<FormatException>(() => LutLoader.ParseCube(text));
  }

  [Test]
  public void ParseCube_AcceptsCommentsBlankLinesAndTitle() {
    const string text = """
# Generated by Test
TITLE "Identity Look"

LUT_3D_SIZE 2

# vertices

0.0 0.0 0.0
1.0 0.0 0.0
0.0 1.0 0.0
1.0 1.0 0.0
0.0 0.0 1.0
1.0 0.0 1.0
0.0 1.0 1.0
1.0 1.0 1.0
""";
    var lut = LutLoader.ParseCube(text);
    Assert.That(lut.Size, Is.EqualTo(2));
  }

  [Test]
  public void ParseCube_AcceptsWindowsAndUnixNewlines() {
    var unixText = BuildIdentityCube("\n");
    var winText  = BuildIdentityCube("\r\n");
    var unix = LutLoader.ParseCube(unixText);
    var win  = LutLoader.ParseCube(winText);
    Assert.Multiple(() => {
      Assert.That(unix.Size, Is.EqualTo(2));
      Assert.That(win.Size,  Is.EqualTo(2));
      Assert.That(win.Table, Is.EqualTo(unix.Table));
    });
  }

  [Test]
  public void ParseCube_DomainMinMax_NormalisesSamplesIntoUnitRange() {
    // Domain 0..2 — all sample values in 0..2 → after normalisation in 0..1.
    const string text = """
LUT_3D_SIZE 2
DOMAIN_MIN 0.0 0.0 0.0
DOMAIN_MAX 2.0 2.0 2.0
0.0 0.0 0.0
2.0 0.0 0.0
0.0 2.0 0.0
2.0 2.0 0.0
0.0 0.0 2.0
2.0 0.0 2.0
0.0 2.0 2.0
2.0 2.0 2.0
""";
    var lut = LutLoader.ParseCube(text);
    Assert.Multiple(() => {
      Assert.That(lut.Table[0],  Is.EqualTo(0f).Within(1e-6));
      Assert.That(lut.Table[3],  Is.EqualTo(1f).Within(1e-6));
      Assert.That(lut.Table[21], Is.EqualTo(1f).Within(1e-6));
    });
  }

  [Test]
  public void Load_DispatchesByExtension_DotCubeAndDot3dl() {
    var dir = new DirectoryInfo(Path.Combine(Path.GetTempPath(), "pm-lut-tests-" + Guid.NewGuid().ToString("N")));
    dir.Create();
    try {
      var cubeFile = new FileInfo(Path.Combine(dir.FullName, "id.cube"));
      File.WriteAllText(cubeFile.FullName, BuildIdentityCube("\n"));
      var lut1 = LutLoader.Load(cubeFile);
      Assert.That(lut1.Size, Is.EqualTo(2));

      var dlFile = new FileInfo(Path.Combine(dir.FullName, "id.3dl"));
      File.WriteAllText(dlFile.FullName, BuildIdentity3dl());
      var lut2 = LutLoader.Load(dlFile);
      Assert.That(lut2.Size, Is.EqualTo(2));
    } finally {
      dir.Delete(recursive: true);
    }
  }

  private static string BuildIdentityCube(string newline) {
    var inv = CultureInfo.InvariantCulture;
    var lines = new List<string> {
      "LUT_3D_SIZE 2",
      "0.0 0.0 0.0",
      "1.0 0.0 0.0",
      "0.0 1.0 0.0",
      "1.0 1.0 0.0",
      "0.0 0.0 1.0",
      "1.0 0.0 1.0",
      "0.0 1.0 1.0",
      "1.0 1.0 1.0",
    };
    return string.Join(newline, lines) + newline;
  }

  private static string BuildIdentity3dl() {
    // 8 vertices on a 0..1023 scale (10-bit). Identity → corner colours.
    var lines = new List<string> {
      "# Identity 3DL",
      "0 0 0",
      "1023 0 0",
      "0 1023 0",
      "1023 1023 0",
      "0 0 1023",
      "1023 0 1023",
      "0 1023 1023",
      "1023 1023 1023",
    };
    return string.Join("\n", lines);
  }
}
